### ISSUE TITLE
make prefix building simpler

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-elb#30]
This is the right configuration for the s3 firehose for elb:

```
firehose:
    type: s3
    params:
       bucket: log-balancer
       prefix: logs/AWSLogs/ID/
       pattern: "([^\n]+).log"
       start-after: "elasticloadbalancing/us-west-1/2017/04/09/"
       gzipped: false
```

- [ ] update the pattern to this one: ```"([^\n]+).log"``` from the complicated regex
- [ ] prefix in this case should just be ```logs```
- [ ] the ID can be fetched and used as default from cloud formation
- [ ] in the start-after param, the region can be a list

**Comment by khou** [comment]
@javasoze 
the cleaner template produces this:

```
firehose:
    type: s3
    params:
       bucket: log-balancer
       prefix: logs/AWSLogs/ID/elasticloadbalancing/us-west-1
       pattern: "([^\n]+).log"
       start-after: "2017/04/09"
       gzipped: false

```
